server:
  port: 2333
spring:
  application:
    name: single-server-shiro
  datasource:
    username: im
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/websocket-im?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
websocket:
  endpoint: /ws
  cross-origins:
    - '*'
  certificate-sign: 'token'

logging:
  level:
    com.him.woll.singleservershiro: debug
  file:
    path:  E:\\github\\websocket-woll\log\single-server-shiro.log

